services:
  - type: web
    name: pharma-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app/main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: STREAMLIT_SERVER_PORT
        value: 8501
      - key: STREAMLIT_SERVER_ADDRESS
        value: 0.0.0.0
    autoDeploy: true
    healthCheckPath: /_stcore/health
    disk:
      name: data
      mountPath: /app/data
      sizeGB: 1